name: Clang Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_CONAN_CLASS: "QwtConan"
  SINTEF_REFERENCE: "qwt*"
  SINTEF_LIBNAME: "qwt"
  CONAN_UPLOAD: "https://api.bintray.com/conan/sintef-ocean/conan"
  CONAN_PASSWORD_SINTEF: ${{ secrets.BINTRAY_API_KEY }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.BINTRAY_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-with-clang:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CC: clang-${{ matrix.compiler_version }}
      CXX: clang++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [8, 9, 10]
        build_type: [Debug, Release]
        option_shared: [shared=True, shared=False]
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan requests
          sudo pip3 install conan_package_tools
          sudo apt-get install libgl1-mesa-dev
          if [ ${{ matrix.compiler_version }} -eq 10 ]; then
              wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
              echo deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main >> clang10.list
              sudo mv clang10.list /etc/apt/sources.list.d/clang10.list
              sudo apt-get update
              sudo apt-get install clang-tools-10
          fi
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libstdc++11 \
            -o ${SINTEF_LIBNAME}:${{ matrix.option_shared }} \
            -b missing -b outdated . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
      - name: Bintray info
        run: |
          python3 bintray.py ${SINTEF_CONAN_CLASS} \
            ${CONAN_LOGIN_USERNAME_SINTEF} ${CONAN_PASSWORD_SINTEF}
