name: GCC Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_CONAN_CLASS: "QwtConan"
  SINTEF_REFERENCE: "qwt*"
  SINTEF_LIBNAME: "qwt"
  CONAN_UPLOAD: "https://api.bintray.com/conan/sintef-ocean/conan"
  CONAN_PASSWORD_SINTEF: ${{ secrets.BINTRAY_API_KEY }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.BINTRAY_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-with-gcc:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [6, 7, 8, 9]
        build_type: [Debug, Release]
        option_shared: [shared=True, shared=False]
        os: [ubuntu-20.04]
    container:
      image: conanio/gcc${{ matrix.compiler_version }}
      options: -u 0
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan requests
          sudo apt-get install -y libgl1-mesa-dev pkg-config
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - name: Conan create
        run: |
          if [ "${{ matrix.build_type }}" == "Debug" ]; then export extra="--build qt/5.1*"; fi
          if [ ${{ matrix.compiler_version }} -eq 6 ]; then
              export EXTRA="-b libx11 -b expat"
          fi
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libstdc++11 \
            -o ${SINTEF_LIBNAME}:${{ matrix.option_shared }} \
            -b missing -b outdated ${EXTRA}\
            . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
      - name: Bintray info
        run: |
          python3 bintray.py ${SINTEF_CONAN_CLASS} \
            ${CONAN_LOGIN_USERNAME_SINTEF} ${CONAN_PASSWORD_SINTEF}
